### PR TITLE
Adding Dockerfile for building cs2kz_metamod with Valve's SDK Docker Image

### PR DESCRIPTION
**Pull request by DizzyThermal**
- Added Dockerfile for building cs2kz_metamod using Valve's SDK Docker Image
- Updated README with instructions on how to build

### CODE REVIEW

**Comment by zer0k-z** [comment]
Could you target the dev branch with the PR instead please?

**Review by DizzyThermal — COMMENTED** [review]
Moved target branch from `master` to `dev`

**Comment by DizzyThermal** [comment]
It looks like some effort already went into creating a Dockerfile for building (that was on the dev branch).

How would you like to see this merged?

**Comment by zer0k-z** [comment]
Since this dockerfile is meant to be ran locally (at least that's what I think), I think you could rename it to something else like `local.Dockerfile` and do `docker build -t cs2kz_metamod_build . -f local.Dockerfile` in the readme instead.

**Comment by zer0k-z** [comment]
Or actually, maybe the better way is to change the steps in readme so it mounts the cloned repository, that way we only need 1 dockerfile.

**Comment by DizzyThermal** [comment]
My Dockerfile clones the repo's master branch and builds off that. The dev branch Dockerfile copies the local git checkout into the Docker container to build, which is better for development.

I think keep the current Dockerfile in `dev`, but then update the README to explain how to use it.

**Comment by DizzyThermal** [comment]
Recreated fork w/ master and dev branches so I could do this PR properly:
https://github.com/zer0k-z/cs2kz_metamod/pull/30

**Pull request closed without merging**
